GET http://localhost:3000/user

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Calebe Pereira de Paula Moura",
    "email": "calebe.moura@hotmail.com",
    "phone": "+55 (21) 99577-8618",
    "cpf": "171.896.827-24",
    "password": "Calebe01*"
}